"""empty message

Revision ID: e792a0fedcd2
Revises: 
Create Date: 2023-05-05 22:59:15.686594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e792a0fedcd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('city_ascii', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.String(length=80), nullable=False),
    sa.Column('lng', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('iso2', sa.String(length=80), nullable=False),
    sa.Column('iso3', sa.String(length=80), nullable=False),
    sa.Column('admin_name', sa.String(length=80), nullable=False),
    sa.Column('capital', sa.String(length=80), nullable=False),
    sa.Column('population', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Data')
    # ### end Alembic commands ###
